// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqgsgrwtxufxebaujegn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZ3Nncnd0eHVmeGViYXVqZWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQzMDUsImV4cCI6MjA3Mzc5MDMwNX0.5OCJfuTQHMfBKNMFaV1VFrlZYvZJ9Xj1ZyIVeyprnho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});